[tar]
extract = "tar xf${verbose} ${filename} -C ${directory}"
compress = "tar caf${verbose} ${filename} -C ${directory} ."
show = "tar tf${verbose} ${filename}"
extensions = [".tar", ".tar.gz", ".bz2", ".xz"]
verbose = "v"

[zip]
extract = "unzip ${filename} -d ${directory}"
compress = "zip -r${verbose} ${filename} ${directory}"
show = "unzip -l${verbose} ${filename}"
extensions = [".zip"]
verbose = "v"

[7z]
extract = "7z x${verbose} ${filename} -o${directory}"
compress = "7z a${verbose} ${filename} ${directory}"
show = "7z l${verbose} ${filename}"
extensions = [".7z"]
verbose = ""

[rar]
extract = "unrar x${verbose} ${filename} ${directory}"
compress = "rar a${verbose} ${filename} ${directory}"
show = "unrar l${verbose} ${filename}"
extensions = [".rar"]
verbose = "v"
